### ISSUE TITLE
No Rain Value

### ISSUE THREAD

**Issue by TMHEINE** [Zwer2k/WeatherStationDataRx#17]
Hello,

First of all thank you for the Project. I am almost very happy with it.
I connected my W177 modules (W132, W174, W186) directly like in the bottom drawing.
I got all values on the original Screen and nearly all values on the Wemos....
expect the RainVolume
On the display it is 15.5mm Total, but in Programm still nothing (-99.99 is declared al default).
Example:
Publish message: {"Unix":1618310638,"Temp":25.10,"Hum":31,"Wind":0.00,"Dir":225,"Gust":0.00,"Rain":-99.99}
Even in your Demo program, i get nothing...

What could be the Problem?

Thanks

**Comment by TMHEINE** [comment]
Hello,
Is the rain Sensor only talking to the Screen, or also to the W132?
Do I have to Connect the Rain Sensor also to the Wemos like the Wind sensor?
If i have to connect more than power? From which Pin on Wemos to where in rain sensor?

Thanks

**Comment by Zwer2k** [comment]
The rain sensor does not talk to W132. 
I take the signal directly from the read contact of the rain sensor, but then I have to calculate the amount of rain myself.
But if you use RXB6/MX-RM-5V, you should get all the values.
