### ISSUE TITLE
Problem with arduinoOTA

### ISSUE THREAD

**Issue by Merlin-33** [Zwer2k/WeatherStationDataRx#6]
Hello,

I signed up on github because I don't know how to ask you for help with your arduino library.
I am putting OTA support but I am having upload problems due to wsdr.begin (); which causes me errors every time. A priori this blocks me the OTA update and I do not know how to stop this function because the wsdr.end (); does not exist according to my IDE compiler ... How can I do? I hope I put it in the right place because I have no idea how Github works ... Thank you

**Comment by Zwer2k** [comment]
Hello,

Which ESP board do you use?

**Comment by Merlin-33** [comment]
hello, so I'm using the Wemos D1 mini ESP card.
I'm trying to see how I can work around my problem, I had a solution with delay (); but it blocks me all, even the OTA update.

**Comment by Merlin-33** [comment]
Ok thank you, my code is not quite the same, but a priori it is a loop which pisses off at the level of the wifi which takes back the hand according to certain people ... Suddenly it does not even work with the solution of your code. So I sought to develop an update system through a button to block the launch of wsdr.begin () and let the OTA update be done. It's not yet finished but I'm almost there, if it works I could say how to do it here, if it's possible :)

**Comment by Zwer2k** [comment]
I have implemented end() function. I hope it helps you with your problem.

**Comment by Merlin-33** [comment]
Ok thanks, so if I do wsdr.end (); this will therefore stop me from all the functions that have been launched by wsdr.begin (); ?

**Comment by Zwer2k** [comment]
Yes exactly.
